language: node_js
node_js:
  - "0.10"
  - "4.0"
script: npm test
env:
  global:
    - POSTGRES_DATABASE="travis_ci_test"
    - DROP_DATABASE="dropdb --if-exists travis_ci_test"
    - CREATE_DATABASE="createdb travis_ci_test"
    - DATABASE_URL="postgres://postgres@localhost/travis_ci_test"
sudo: false
addons:
  postgresql: "9.3"
  postgresql: "9.4"
