language: node_js
script: npm test
env:
  global:
    - POSTGRES_DATABASE="travis_ci_test"
    - DROP_DATABASE="dropdb --if-exists travis_ci_test"
    - CREATE_DATABASE="createdb travis_ci_test"
    - DATABASE_URL="postgres://postgres@localhost/travis_ci_test"
sudo: false
matrix:
  include:
    - node_js: "0.10"
      addons:
        postgresql: "9.4"
    - node_js: "4.0"
      addons:
        postgresql: "9.4"
    - node_js: "4.0"
      addons:
        postgresql: "9.3"
